<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><NuGetAudit>false</NuGetAudit></PropertyGroup>
  <ItemGroup>
    <Reference Include="AuswertungPro.Next.Infrastructure"><HintPath>../../src/AuswertungPro.Next.Infrastructure/bin/Release/net10.0/AuswertungPro.Next.Infrastructure.dll</HintPath></Reference>
    <Reference Include="AuswertungPro.Next.Domain"><HintPath>../../src/AuswertungPro.Next.Domain/bin/Release/net10.0/AuswertungPro.Next.Domain.dll</HintPath></Reference>
    <Reference Include="AuswertungPro.Next.Application"><HintPath>../../src/AuswertungPro.Next.Application/bin/Release/net10.0/AuswertungPro.Next.Application.dll</HintPath></Reference>
  </ItemGroup>
</Project>
