using System;
using System.IO;
using static AuswertungPro.Next.UI.Tests.SourceTextTestHelpers;

namespace AuswertungPro.Next.UI.Tests;

public sealed class PlayerWindowLiveDetectionConfirmationArchitectureTests
{
    [Fact]
    public void PlayerWindow_live_detection_confirmation_actions_live_in_actions_partial()
    {
        var root = FindRepositoryRoot();
        var uiRoot = Path.Combine(root, "src", "AuswertungPro.Next.UI");
        var windowsRoot = Path.Combine(uiRoot, "Views", "Windows");
        var confirmationPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Confirmation.cs");
        var actionsPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Confirmation.Actions.cs");
        var trainingPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Confirmation.Training.cs");
        var statusControlsPath = Path.Combine(windowsRoot, "LiveDetectionStatusControls.cs");
        var correctionSelectionPath = Path.Combine(uiRoot, "Ai", "LiveDetectionCorrectionCodeSelectionService.cs");
        var correctionSelectionFactoryPath = Path.Combine(uiRoot, "Ai", "LiveDetectionCorrectionCodeSelectionServiceFactory.cs");
        var correctionSelectionWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionCorrectionCodeSelectionWorkflow.cs");
        var displayWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationDisplayWorkflow.cs");
        var frameExporterPath = Path.Combine(uiRoot, "Ai", "LiveDetectionTrainingFrameExporter.cs");
        var exportPlannerPath = Path.Combine(uiRoot, "Ai", "LiveDetectionTrainingExportPlanner.cs");
        var annotationWriterPath = Path.Combine(uiRoot, "Ai", "LiveDetectionTrainingAnnotationWriter.cs");
        var trainingWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationTrainingWorkflow.cs");
        var trainingResultWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationTrainingResultWorkflow.cs");
        var acceptCommandWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationAcceptCommandWorkflow.cs");
        var correctCommandWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationCorrectCommandWorkflow.cs");
        var skipCommandWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionConfirmationSkipCommandWorkflow.cs");

        Assert.True(File.Exists(actionsPath), "LiveDetection-Bestaetigungsaktionen sollen aus dem Anzeige-Partial heraus.");
        Assert.True(File.Exists(trainingPath), "LiveDetection-Trainingsuebernahme soll aus den simplen Bestaetigungsaktionen heraus.");
        Assert.True(File.Exists(correctionSelectionPath), "LiveDetection-Korrektur-Codeauswahl soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(correctionSelectionFactoryPath), "LiveDetection-Korrektur-Codeauswahl soll ueber Factory verdrahtet werden.");
        Assert.True(File.Exists(correctionSelectionWorkflowPath), "LiveDetection-Korrektur-Codeauswahl-Serviceaufruf soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(displayWorkflowPath), "LiveDetection-Bestaetigungsanzeige und Resume-Entscheidung sollen ausserhalb von PlayerWindow liegen.");
        Assert.True(File.Exists(frameExporterPath), "Detection-Training-Frame-Export soll ausserhalb der PlayerWindow-Partials gekapselt sein.");
        Assert.True(File.Exists(exportPlannerPath), "Detection-Training-Exportplanung soll ausserhalb der PlayerWindow-Partials gekapselt sein.");
        Assert.True(File.Exists(annotationWriterPath), "Detection-Training-Annotationen sollen ausserhalb der PlayerWindow-Partials geschrieben werden.");
        Assert.True(File.Exists(trainingWorkflowPath), "Detection-Confirmation-Training-Ablauf soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(trainingResultWorkflowPath), "Detection-Confirmation-Training-Ergebnisbehandlung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(acceptCommandWorkflowPath), "Detection-Accept-Befehlsreihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(correctCommandWorkflowPath), "Detection-Correct-Befehlsreihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(skipCommandWorkflowPath), "Detection-Skip-Befehlsreihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");

        var confirmation = File.ReadAllText(confirmationPath);
        var actions = File.ReadAllText(actionsPath);
        var training = File.ReadAllText(trainingPath);
        var statusControls = File.ReadAllText(statusControlsPath);
        var correctionSelection = File.ReadAllText(correctionSelectionPath);
        var correctionSelectionFactory = File.ReadAllText(correctionSelectionFactoryPath);
        var correctionSelectionWorkflow = File.Exists(correctionSelectionWorkflowPath) ? File.ReadAllText(correctionSelectionWorkflowPath) : "";
        var displayWorkflow = File.Exists(displayWorkflowPath) ? File.ReadAllText(displayWorkflowPath) : "";
        var frameExporter = File.ReadAllText(frameExporterPath);
        var exportPlanner = File.ReadAllText(exportPlannerPath);
        var annotationWriter = File.ReadAllText(annotationWriterPath);
        var trainingWorkflow = File.Exists(trainingWorkflowPath) ? File.ReadAllText(trainingWorkflowPath) : "";
        var trainingResultWorkflow = File.Exists(trainingResultWorkflowPath) ? File.ReadAllText(trainingResultWorkflowPath) : "";
        var acceptCommandWorkflow = File.Exists(acceptCommandWorkflowPath) ? File.ReadAllText(acceptCommandWorkflowPath) : "";
        var correctCommandWorkflow = File.Exists(correctCommandWorkflowPath) ? File.ReadAllText(correctCommandWorkflowPath) : "";
        var skipCommandWorkflow = File.Exists(skipCommandWorkflowPath) ? File.ReadAllText(skipCommandWorkflowPath) : "";

        Assert.Contains("private void ShowDetectionConfirmation", confirmation);
        Assert.Contains("private void ResumeDetection", confirmation);
        Assert.Contains("LiveDetectionConfirmationDisplayWorkflow.Show", confirmation);
        Assert.Contains("LiveDetectionConfirmationDisplayWorkflow.Resume", confirmation);
        Assert.DoesNotContain("PlayerConfirmationPlayback.PauseLiveDetectionConfirmation", confirmation);
        Assert.DoesNotContain("if (_detectionConfirmationBuffer.TimestampSeconds.HasValue)", confirmation);
        Assert.DoesNotContain("if (!_playerPlaybackControlHost.IsPlaying)", confirmation);
        Assert.Contains("LiveDetectionStatusControls.ShowDetectionConfirmation", confirmation);
        Assert.Contains("LiveDetectionStatusControls.HideDetectionConfirmation", confirmation);
        Assert.DoesNotContain("TxtDetectionFinding.Text", confirmation);
        Assert.DoesNotContain("TxtDetectionDetail.Text", confirmation);
        Assert.DoesNotContain("DetectionConfirmationPanel.Visibility = Visibility.Visible", confirmation);
        Assert.DoesNotContain("DetectionConfirmationPanel.Visibility = Visibility.Collapsed", confirmation);
        Assert.DoesNotContain("private async void DetectionAccept_Click", confirmation);
        Assert.DoesNotContain("private async void DetectionCorrect_Click", confirmation);
        Assert.DoesNotContain("private void DetectionSkip_Click", confirmation);
        Assert.DoesNotContain("private async void DetectionAccept_Click", actions);
        Assert.DoesNotContain("private async void DetectionCorrect_Click", actions);
        Assert.Contains("private void DetectionSkip_Click", actions);
        Assert.Contains("LiveDetectionConfirmationSkipCommandWorkflow.Execute", actions);
        Assert.DoesNotContain("ResumeDetection();", actions);
        Assert.DoesNotContain("TrainingAnnotationExportServiceFactory.Create", actions);
        Assert.DoesNotContain("private async void DetectionAccept_Click", training);
        Assert.DoesNotContain("private async void DetectionCorrect_Click", training);
        Assert.Contains("private void DetectionAccept_Click", training);
        Assert.Contains("private void DetectionCorrect_Click", training);
        Assert.Contains(".SafeFireAndForget(\"DetectionAccept\")", training);
        Assert.Contains(".SafeFireAndForget(\"DetectionCorrect\")", training);
        Assert.Contains("private async Task HandleDetectionAcceptAsync", training);
        Assert.Contains("private async Task HandleDetectionCorrectAsync", training);
        Assert.Contains("LiveDetectionConfirmationAcceptCommandWorkflow.ExecuteAsync", training);
        Assert.DoesNotContain("if (pendingFindings.Count == 0)", training);
        Assert.DoesNotContain("\n        try", training);
        Assert.DoesNotContain("catch (Exception ex)", training);
        Assert.Contains("LiveDetectionConfirmationCorrectCommandWorkflow.ExecuteAsync", training);
        Assert.DoesNotContain("selectedEntry == null", training);
        Assert.Contains("LiveDetectionCorrectionCodeSelectionWorkflow.Select", training);
        Assert.DoesNotContain("LiveDetectionCorrectionCodeSelectionServiceFactory.Create", training);
        Assert.DoesNotContain("CodingExplorerEntryFactory.CreateSeed", training);
        Assert.DoesNotContain("VsaCodeExplorerDialogServiceFactory.Create", training);
        Assert.Contains("LiveDetectionTrainingAnnotationWriter.CreateDefault", training);
        Assert.Contains("LiveDetectionConfirmationTrainingWorkflow.SaveAcceptedAsync", training);
        Assert.Contains("LiveDetectionConfirmationTrainingWorkflow.SaveCorrectedAsync", training);
        Assert.Contains("LiveDetectionConfirmationTrainingResultWorkflow.ExecuteAccepted", training);
        Assert.Contains("LiveDetectionConfirmationTrainingResultWorkflow.ExecuteCorrected", training);
        Assert.Contains("var trainingResult = await actions.SaveAcceptedAsync()", acceptCommandWorkflow);
        Assert.Contains("actions.HandleAcceptedResult(trainingResult)", acceptCommandWorkflow);
        Assert.Contains("actions.ShowOsdMeterStatus($\"\\u2717 Fehler: {ex.Message}\", false)", acceptCommandWorkflow);
        Assert.Contains("actions.ResumeDetection()", acceptCommandWorkflow);
        Assert.Contains("var selectedEntry = actions.SelectCorrection()", correctCommandWorkflow);
        Assert.Contains("var trainingResult = await actions.SaveCorrectedAsync(selectedEntry)", correctCommandWorkflow);
        Assert.Contains("actions.HandleCorrectedResult(trainingResult)", correctCommandWorkflow);
        Assert.Contains("actions.ShowOsdMeterStatus($\"\\u2717 Fehler: {ex.Message}\", false)", correctCommandWorkflow);
        Assert.Contains("actions.ResumeDetection()", correctCommandWorkflow);
        Assert.Contains("actions.ResumeDetection()", skipCommandWorkflow);
        Assert.DoesNotContain("if (!result.Saved)", training);
        Assert.DoesNotContain("result.SavedCount", training);
        Assert.DoesNotContain("result.Code", training);
        Assert.Contains("public static void ShowDetectionConfirmation", statusControls);
        Assert.Contains("public static void HideDetectionConfirmation", statusControls);
        Assert.Contains("PlayerConfirmationPlayback.PauseLiveDetectionConfirmation", displayWorkflow);
        Assert.Contains("SeekMilliseconds", displayWorkflow);
        Assert.DoesNotContain("foreach (var finding in _detectionPendingFindings)", training);
        Assert.DoesNotContain("annotationWriter.SaveAcceptedAsync", training);
        Assert.DoesNotContain("annotationWriter.SaveCorrectedAsync", training);
        Assert.Contains("CodingExplorerEntryFactory.CreateSeed", correctionSelection);
        Assert.Contains("VsaCodeExplorerDialogServiceFactory.Create", correctionSelectionFactory);
        Assert.Contains("LiveDetectionCorrectionCodeSelectionServiceFactory.Create", correctionSelectionWorkflow);
        Assert.Contains("service.Select(", correctionSelectionWorkflow);
        Assert.DoesNotContain("TrainingAnnotationExportServiceFactory.Create", training);
        Assert.DoesNotContain("LiveDetectionTrainingFrameExporter", training);
        Assert.DoesNotContain("LiveDetectionTrainingExportPlanner.BuildAccepted", training);
        Assert.DoesNotContain("LiveDetectionTrainingExportPlanner.BuildCorrected", training);
        Assert.DoesNotContain("VsaYoloClassMap.GetClassId", training);
        Assert.DoesNotContain("BBoxFromClockPosition", training);
        Assert.DoesNotContain("det_corr_", training);
        Assert.DoesNotContain("File.WriteAllBytesAsync", training);
        Assert.DoesNotContain("File.Delete", training);
        Assert.DoesNotContain("Path.GetTempPath", training);
        Assert.DoesNotContain("TeacherAnnotationStore.AppendAsync", training);
        Assert.Contains("public sealed class LiveDetectionTrainingFrameExporter", frameExporter);
        Assert.Contains("File.WriteAllBytesAsync", frameExporter);
        Assert.Contains("BestEffort.Try", frameExporter);
        Assert.Contains("public static class LiveDetectionTrainingExportPlanner", exportPlanner);
        Assert.Contains("VsaYoloClassMap.GetClassId", exportPlanner);
        Assert.Contains("LiveDetectionGeometryMapper.BBoxFromClockPosition", exportPlanner);
        Assert.Contains("public sealed class LiveDetectionTrainingAnnotationWriter", annotationWriter);
        Assert.Contains("TrainingAnnotationExportServiceFactory.Create", annotationWriter);
        Assert.Contains("LiveDetectionTrainingExportPlanner.BuildAccepted", annotationWriter);
        Assert.Contains("LiveDetectionTrainingExportPlanner.BuildCorrected", annotationWriter);
        Assert.Contains("TeacherAnnotationStore.AppendAsync", annotationWriter);
        Assert.Contains("saveAcceptedAsync", trainingWorkflow);
        Assert.Contains("saveCorrectedAsync", trainingWorkflow);
        Assert.Contains("if (!trainingResult.Saved)", trainingResultWorkflow);
        Assert.Contains("actions.ShowOsdMeterStatus($\"\\u2713 {trainingResult.SavedCount} Befund(e) gespeichert\", true)", trainingResultWorkflow);
        Assert.Contains("actions.ShowOsdMeterStatus($\"\\u2713 Training: {trainingResult.Code} (korrigiert)\", true)", trainingResultWorkflow);
        Assert.Contains("actions.ResumeDetection()", trainingResultWorkflow);
    }
}
