using System;
using System.IO;
using System.Linq;
using static AuswertungPro.Next.UI.Tests.TestRepoPaths;

namespace AuswertungPro.Next.UI.Tests;

public sealed class PlayerWindowWiringArchitectureTests
{
    [Fact]
    public void PlayerWindow_constructor_wiring_lives_in_wiring_partial()
    {
        var root = FindRepositoryRoot();
        var uiRoot = Path.Combine(root, "src", "AuswertungPro.Next.UI");
        var windowsRoot = Path.Combine(uiRoot, "Views", "Windows");
        var windowRootPath = Path.Combine(windowsRoot, "PlayerWindow.xaml.cs");
        var wiringPath = Path.Combine(windowsRoot, "PlayerWindow.Wiring.cs");
        var lifecycleEventBinderPath = Path.Combine(windowsRoot, "PlayerLifecycleEventBinder.cs");
        var surfaceEventBinderPath = Path.Combine(windowsRoot, "PlayerSurfaceEventBinder.cs");
        var dispatcherSchedulerPath = Path.Combine(windowsRoot, "PlayerDispatcherScheduler.cs");
        var focusControlsPath = Path.Combine(windowsRoot, "PlayerFocusControls.cs");
        var chromeControlsPath = Path.Combine(windowsRoot, "PlayerChromeControls.cs");
        var applicationControlsPath = Path.Combine(windowsRoot, "PlayerApplicationControls.cs");
        var sliderPath = Path.Combine(windowsRoot, "PlayerWindow.Wiring.PositionSlider.cs");
        var sliderEventBinderPath = Path.Combine(windowsRoot, "PlayerPositionSliderEventBinder.cs");
        var keyboardEventBinderPath = Path.Combine(windowsRoot, "PlayerKeyboardEventBinder.cs");
        var statePath = Path.Combine(windowsRoot, "PlayerWindow.State.cs");
        var dragPlaybackPath = Path.Combine(uiRoot, "Player", "PlayerPositionSliderDragPlayback.cs");
        var dragWorkflowPath = Path.Combine(uiRoot, "Player", "PlayerPositionSliderDragWorkflow.cs");
        var sliderStateControllerPath = Path.Combine(uiRoot, "Player", "PlayerPositionSliderStateController.cs");
        var activationWorkflowPath = Path.Combine(uiRoot, "Player", "PlayerWindowActivationWorkflow.cs");
        var loadedWorkflowPath = Path.Combine(uiRoot, "Player", "PlayerWindowLoadedWorkflow.cs");
        var headerControlsPath = Path.Combine(uiRoot, "Player", "PlayerWindowHeaderControls.cs");
        var stateControlsPath = Path.Combine(uiRoot, "Player", "PlayerWindowStateControls.cs");
        var closedWorkflowPath = Path.Combine(uiRoot, "Player", "PlayerWindowClosedWorkflow.cs");
        var controllerSetFactoryPath = Path.Combine(uiRoot, "Player", "PlayerWindowControllerSetFactory.cs");
        var controllerSetInitializerPath = Path.Combine(windowsRoot, "PlayerWindowControllerSetInitializer.cs");

        Assert.True(File.Exists(wiringPath), "Fenster-, Slider- und Viewport-Wiring soll aus dem Konstruktor heraus.");
        Assert.True(File.Exists(lifecycleEventBinderPath), "Fenster-Lifecycle-Event-Binding soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(surfaceEventBinderPath), "Fenster-Surface-Event-Binding soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(dispatcherSchedulerPath), "Dispatcher-Scheduling soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(focusControlsPath), "Fenster-Focus- und Aktivierungsoberflaeche soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(chromeControlsPath), "Fenster-Chrome-Zustand soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(applicationControlsPath), "Application-MainWindow-Zugriff soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(sliderPath), "PositionSlider-Wiring soll in einem eigenen Wiring-Partial liegen.");
        Assert.True(File.Exists(sliderEventBinderPath), "PositionSlider-Event-Binding soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(keyboardEventBinderPath), "Keyboard-Event-Binding soll ausserhalb der PlayerWindow-Partials gebuendelt werden.");
        Assert.True(File.Exists(dragPlaybackPath), "PositionSlider-Drag-Pause-Regel muss ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(dragWorkflowPath), "PositionSlider-Drag-Reihenfolge muss ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(sliderStateControllerPath), "PositionSlider-Drag-Zustand soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(activationWorkflowPath), "Fenster-Aktivierungs-Entscheidung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(loadedWorkflowPath), "Fenster-Loaded-Reihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(headerControlsPath), "Player-Header-Control-Zuweisungen sollen ausserhalb des Konstruktors liegen.");
        Assert.True(File.Exists(stateControlsPath), "WindowStateManager-Zugriff soll ausserhalb des PlayerWindow-Konstruktors liegen.");
        Assert.True(File.Exists(closedWorkflowPath), "Closed-Cleanup-Reihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(controllerSetFactoryPath), "PlayerWindow-Controller-Konstruktion soll ausserhalb des Konstruktors gebuendelt werden.");
        Assert.True(File.Exists(controllerSetInitializerPath), "PlayerWindow-Control-Mapping fuer Controller soll ausserhalb des Konstruktors liegen.");

        var windowRoot = File.ReadAllText(windowRootPath);
        var wiring = File.ReadAllText(wiringPath);
        var lifecycleEventBinder = File.Exists(lifecycleEventBinderPath) ? File.ReadAllText(lifecycleEventBinderPath) : "";
        var surfaceEventBinder = File.Exists(surfaceEventBinderPath) ? File.ReadAllText(surfaceEventBinderPath) : "";
        var dispatcherScheduler = File.Exists(dispatcherSchedulerPath) ? File.ReadAllText(dispatcherSchedulerPath) : "";
        var focusControls = File.Exists(focusControlsPath) ? File.ReadAllText(focusControlsPath) : "";
        var chromeControls = File.Exists(chromeControlsPath) ? File.ReadAllText(chromeControlsPath) : "";
        var applicationControls = File.Exists(applicationControlsPath) ? File.ReadAllText(applicationControlsPath) : "";
        var slider = File.ReadAllText(sliderPath);
        var sliderEventBinder = File.Exists(sliderEventBinderPath) ? File.ReadAllText(sliderEventBinderPath) : "";
        var keyboardEventBinder = File.Exists(keyboardEventBinderPath) ? File.ReadAllText(keyboardEventBinderPath) : "";
        var state = File.ReadAllText(statePath);
        var dragPlayback = File.Exists(dragPlaybackPath) ? File.ReadAllText(dragPlaybackPath) : "";
        var dragWorkflow = File.Exists(dragWorkflowPath) ? File.ReadAllText(dragWorkflowPath) : "";
        var sliderStateController = File.Exists(sliderStateControllerPath) ? File.ReadAllText(sliderStateControllerPath) : "";
        var activationWorkflow = File.Exists(activationWorkflowPath) ? File.ReadAllText(activationWorkflowPath) : "";
        var loadedWorkflow = File.Exists(loadedWorkflowPath) ? File.ReadAllText(loadedWorkflowPath) : "";
        var headerControls = File.Exists(headerControlsPath) ? File.ReadAllText(headerControlsPath) : "";
        var stateControls = File.Exists(stateControlsPath) ? File.ReadAllText(stateControlsPath) : "";
        var closedWorkflow = File.Exists(closedWorkflowPath) ? File.ReadAllText(closedWorkflowPath) : "";
        var controllerSetFactory = File.Exists(controllerSetFactoryPath) ? File.ReadAllText(controllerSetFactoryPath) : "";
        var controllerSetInitializer = File.Exists(controllerSetInitializerPath) ? File.ReadAllText(controllerSetInitializerPath) : "";

        Assert.Contains("_playerControllers = PlayerWindowControllerSetInitializer.Create", windowRoot);
        Assert.DoesNotContain("new PlayerWindowControllerSetControls(", windowRoot);
        Assert.Contains("new PlayerWindowControllerSetControls(", controllerSetInitializer);
        Assert.Contains("window.DamageMarkerCanvas", controllerSetInitializer);
        Assert.DoesNotContain("var controllerSet = PlayerWindowControllerSetFactory.Create", windowRoot);
        Assert.DoesNotContain("= controllerSet.", windowRoot);
        Assert.DoesNotContain("new DamageMarkerController", windowRoot);
        Assert.DoesNotContain("new QuickScanController", windowRoot);
        Assert.DoesNotContain("new PlayerPositionControls", windowRoot);
        Assert.DoesNotContain("new PlayerSpeedControls", windowRoot);
        Assert.DoesNotContain("new PlayerMarkToolControls", windowRoot);
        Assert.DoesNotContain("new CodingOverlayRenderController", windowRoot);
        Assert.Contains("new DamageMarkerController", controllerSetFactory);
        Assert.Contains("new QuickScanController", controllerSetFactory);
        Assert.Contains("new PlayerPositionControls", controllerSetFactory);
        Assert.Contains("new PlayerSpeedControls", controllerSetFactory);
        Assert.Contains("new PlayerMarkToolControls", controllerSetFactory);
        Assert.Contains("new CodingOverlayRenderController", controllerSetFactory);
        Assert.Contains("WireWindowLifecycleEvents();", windowRoot);
        Assert.Contains("WirePositionSliderEvents();", windowRoot);
        Assert.Contains("WireWindowSurfaceEvents();", windowRoot);
        Assert.Contains("PlayerWindowHeaderControls.ApplyVideoInfo", windowRoot);
        Assert.Contains("PlayerWindowStateControls.Track(this)", windowRoot);
        Assert.DoesNotContain("WindowStateManager.Track(this)", windowRoot);
        Assert.Contains("WindowStateManager.Track", stateControls);
        Assert.DoesNotContain("VideoNameText.Text", windowRoot);
        Assert.DoesNotContain("VideoPathText.Text", windowRoot);
        Assert.Contains("public static void ApplyVideoInfo", headerControls);
        Assert.DoesNotContain("PositionSlider.AddHandler", windowRoot);
        Assert.DoesNotContain("Closed += (_, __)", windowRoot);
        Assert.DoesNotContain("Deactivated += (_, _)", windowRoot);
        Assert.Contains("private void WireWindowLifecycleEvents", wiring);
        Assert.Contains("PlayerLifecycleEventBinder.Bind", wiring);
        Assert.DoesNotContain("Loaded += PlayerWindow_EnsureVisibleOnLoaded", wiring);
        Assert.DoesNotContain("Deactivated += PlayerWindow_Deactivated", wiring);
        Assert.DoesNotContain("Activated += PlayerWindow_Activated", wiring);
        Assert.DoesNotContain("Closing += OnClosing", wiring);
        Assert.DoesNotContain("Loaded += PlayerWindow_Loaded", wiring);
        Assert.DoesNotContain("Closed += PlayerWindow_Closed", wiring);
        Assert.Contains("window.Loaded += ensureVisibleOnLoaded", lifecycleEventBinder);
        Assert.Contains("window.Closing += closing", lifecycleEventBinder);
        Assert.Contains("private void WireWindowSurfaceEvents", wiring);
        Assert.Contains("PlayerSurfaceEventBinder.Bind", wiring);
        Assert.DoesNotContain("DamageMarkerCanvas.SizeChanged +=", wiring);
        Assert.DoesNotContain("HeatmapCanvas.SizeChanged +=", wiring);
        Assert.DoesNotContain("DetectionCanvas.MouseLeftButtonDown +=", wiring);
        Assert.DoesNotContain("VideoView.SizeChanged +=", wiring);
        Assert.DoesNotContain("SizeChanged += (_, __) => UpdateCodingOverlayViewport()", wiring);
        Assert.DoesNotContain("LocationChanged += (_, __) => UpdateCodingOverlayViewport()", wiring);
        Assert.Contains("damageMarkerSurface.SizeChanged += damageMarkerSizeChanged", surfaceEventBinder);
        Assert.Contains("window.LocationChanged += windowLocationChanged", surfaceEventBinder);
        Assert.Contains("private void WireKeyboardEvents", wiring);
        Assert.Contains("PlayerKeyboardEventBinder.Bind", wiring);
        Assert.DoesNotContain("AddHandler(Keyboard.PreviewKeyDownEvent", wiring);
        Assert.DoesNotContain("new KeyEventHandler", wiring);
        Assert.Contains(".AddHandler(Keyboard.PreviewKeyDownEvent", keyboardEventBinder);
        Assert.Contains("private void PlayerWindow_Closed", wiring);
        Assert.Contains("PlayerWindowActivationWorkflow.Deactivate", wiring);
        Assert.Contains("PlayerWindowActivationWorkflow.Activate", wiring);
        Assert.Contains("PlayerWindowLoadedWorkflow.Execute", wiring);
        Assert.Contains("PlayerDispatcherScheduler.ScheduleLoaded", wiring);
        Assert.Contains("PlayerDispatcherScheduler.ScheduleInput", wiring);
        Assert.Contains("PlayerFocusControls.ActivateWindow(this)", wiring);
        Assert.Contains("PlayerFocusControls.FocusWindowKeyboard(this)", wiring);
        Assert.Contains("PlayerFocusControls.ActivateWindow(main!)", wiring);
        Assert.Contains("PlayerChromeControls.EnableFocusable(this)", wiring);
        Assert.Contains("PlayerChromeControls.IsMinimized(main)", wiring);
        Assert.Contains("PlayerChromeControls.RestoreNormal(main!)", wiring);
        Assert.Contains("PlayerApplicationControls.CurrentMainWindow()", wiring);
        Assert.DoesNotContain("Dispatcher.BeginInvoke", wiring);
        Assert.DoesNotContain("new Action(UpdateCodingOverlayViewport)", wiring);
        Assert.DoesNotContain("System.Windows.Application.Current?.MainWindow", wiring);
        Assert.DoesNotContain("Application.Current", wiring);
        Assert.DoesNotContain("Keyboard.Focus(this)", wiring);
        Assert.DoesNotContain("Focus();", wiring);
        Assert.DoesNotContain("Activate();", wiring);
        Assert.DoesNotContain("main!.Activate()", wiring);
        Assert.DoesNotContain("Focusable = true", wiring);
        Assert.DoesNotContain("main?.WindowState == WindowState.Minimized", wiring);
        Assert.DoesNotContain("main!.WindowState = WindowState.Normal", wiring);
        Assert.Contains("DispatcherPriority.Loaded", dispatcherScheduler);
        Assert.Contains("DispatcherPriority.Input", dispatcherScheduler);
        Assert.Contains("public static bool FocusElement", focusControls);
        Assert.Contains("public static IInputElement? FocusWindowKeyboard", focusControls);
        Assert.Contains("public static bool ActivateWindow", focusControls);
        Assert.Contains("public static void EnableFocusable", chromeControls);
        Assert.Contains("public static bool IsMinimized", chromeControls);
        Assert.Contains("public static void RestoreNormal", chromeControls);
        Assert.Contains("public static Window? CurrentMainWindow()", applicationControls);
        Assert.Contains("Application.Current?.MainWindow", applicationControls);
        Assert.DoesNotContain("if (_codingOverlaySuspendDepth > 0)", wiring);
        Assert.DoesNotContain("if (!_deactivatedByExternalWindow)", wiring);
        Assert.DoesNotContain("if (!string.IsNullOrWhiteSpace(_initialOverlayText))", wiring);
        Assert.Contains("PlayerWindowClosedWorkflow.Execute", wiring);
        Assert.Contains("public static class PlayerWindowClosedWorkflow", closedWorkflow);
        Assert.Contains("request.CodingOverlaySuspendDepth", activationWorkflow);
        Assert.Contains("actions.HideCodingOverlayForExternalWindow()", activationWorkflow);
        Assert.Contains("actions.RestoreCodingOverlayAfterExternalWindow()", activationWorkflow);
        Assert.Contains("request.InitialOverlayText", loadedWorkflow);
        Assert.Contains("actions.ScheduleLoadedViewportUpdate()", loadedWorkflow);
        Assert.Contains("actions.ShowOverlay", loadedWorkflow);
        Assert.Contains("actions.StopCodingOsdTimer()", closedWorkflow);
        Assert.Contains("actions.StopLiveDetection()", closedWorkflow);
        Assert.DoesNotContain("Codier-Modus sauber", wiring);
        Assert.DoesNotContain("Cleanup() ist idempotent", wiring);
        Assert.DoesNotContain("private void WirePositionSliderEvents", wiring);
        Assert.DoesNotContain("PositionSlider.AddHandler", wiring);
        Assert.Contains("private void WirePositionSliderEvents", slider);
        Assert.Contains("PlayerPositionSliderEventBinder.Bind", slider);
        Assert.DoesNotContain("PositionSlider.AddHandler", slider);
        Assert.DoesNotContain("new DragStartedEventHandler", slider);
        Assert.DoesNotContain("new DragCompletedEventHandler", slider);
        Assert.Contains(".AddHandler(Thumb.DragStartedEvent", sliderEventBinder);
        Assert.Contains(".AddHandler(Thumb.DragCompletedEvent", sliderEventBinder);
        Assert.Contains("private void PositionSlider_DragStarted", slider);
        Assert.Contains("private void PositionSlider_LostMouseCapture", slider);
        Assert.Contains("PlayerPositionSliderDragWorkflow.Start", slider);
        Assert.Contains("PlayerPositionSliderDragWorkflow.Complete", slider);
        Assert.Contains("PlayerPositionSliderDragWorkflow.PreviewMouseUp", slider);
        Assert.Contains("PlayerPositionSliderDragWorkflow.LostMouseCapture", slider);
        Assert.DoesNotContain("if (!_isDragging)", slider);
        Assert.DoesNotContain("_isDragging = false", slider);
        Assert.DoesNotContain("private bool _isDragging", state);
        Assert.DoesNotContain("private bool _wasPlayingBeforeDrag", state);
        Assert.DoesNotContain("private DateTime _lastScrubSeek", state);
        Assert.DoesNotContain("private readonly PlayerPositionSliderStateController _positionSliderStateController = new();", state);
        Assert.Contains("private PlayerPositionSliderStateController _positionSliderStateController => _playerControllers.PositionSliderStateController", state);
        Assert.Contains("_positionSliderStateController.IsDragging", slider);
        Assert.Contains("_positionSliderStateController.WasPlayingBeforeDrag", slider);
        Assert.Contains("_positionSliderStateController.CreateDragActions", slider);
        Assert.DoesNotContain("SetDragging: value => _isDragging = value", slider);
        Assert.DoesNotContain("SetWasPlayingBeforeDrag: value => _wasPlayingBeforeDrag = value", slider);
        Assert.Contains("PlayerPositionSliderDragPlayback.Start", dragWorkflow);
        Assert.Contains("PlayerPositionSliderDragPlayback.Complete", dragWorkflow);
        Assert.DoesNotContain("_player.SetPause(true)", slider);
        Assert.DoesNotContain("_player.SetPause(false)", slider);
        Assert.Contains("public static class PlayerPositionSliderDragPlayback", dragPlayback);
        Assert.Contains("public static class PlayerPositionSliderDragWorkflow", dragWorkflow);
        Assert.Contains("public sealed class PlayerPositionSliderStateController", sliderStateController);
        Assert.Contains("public bool IsDragging", sliderStateController);
        Assert.Contains("public bool WasPlayingBeforeDrag", sliderStateController);
        Assert.Contains("private void WireWindowSurfaceEvents", wiring);
    }
}
