using System;
using System.IO;
using System.Linq;
using static AuswertungPro.Next.UI.Tests.SourceTextTestHelpers;

namespace AuswertungPro.Next.UI.Tests;

public sealed class PlayerWindowLiveDetectionArchitectureTests
{
    [Fact]
    public void PlayerWindow_live_detection_status_lives_in_status_partial()
    {
        var root = FindRepositoryRoot();
        var uiRoot = Path.Combine(root, "src", "AuswertungPro.Next.UI");
        var windowsRoot = Path.Combine(uiRoot, "Views", "Windows");
        var liveDetectionPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.cs");
        var statusPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Status.cs");
        var pulsePath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Status.Pulse.cs");
        var errorWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionErrorWorkflow.cs");
        var snapshotWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionSnapshotWorkflow.cs");
        var runCommandWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionRunCommandWorkflow.cs");
        var pulseWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionPulseWorkflow.cs");
        var pulseStatePath = Path.Combine(uiRoot, "Player", "LiveDetectionPulseStateController.cs");
        var codingAiStateWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionCodingAiStateWorkflow.cs");
        var uiDispatchWorkflowPath = Path.Combine(uiRoot, "Player", "PlayerUiDispatchWorkflow.cs");
        var controlsPath = Path.Combine(windowsRoot, "LiveDetectionStatusControls.cs");
        var pulseControlsPath = Path.Combine(windowsRoot, "LiveDetectionPulseControls.cs");
        var codingStatePath = Path.Combine(windowsRoot, "PlayerWindow.Coding.State.cs");

        Assert.True(File.Exists(statusPath), "LiveDetection-Status-UI soll in ein eigenes Partial.");
        Assert.True(File.Exists(pulsePath), "Coding-AI-Pulsanimation soll aus dem Status-Orchestrator heraus.");
        Assert.True(File.Exists(errorWorkflowPath), "LiveDetection-Fehlerentscheidung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(snapshotWorkflowPath), "LiveDetection-Snapshot-Entscheidung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(runCommandWorkflowPath), "LiveDetection-Run-Orchestrierung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(pulseWorkflowPath), "Coding-AI-Puls-Start/Stop-Reihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(pulseStatePath), "Coding-AI-Puls-Running-State soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(codingAiStateWorkflowPath), "Coding-AI-Status/Puls-Entscheidung soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(uiDispatchWorkflowPath), "Status-UI-Thread-Dispatch soll ausserhalb der PlayerWindow-Partials entschieden werden.");
        Assert.True(File.Exists(controlsPath), "LiveDetection-Status-Control-Zuweisungen sollen ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(pulseControlsPath), "Coding-AI-Pulsanimation soll ausserhalb der PlayerWindow-Partials gesetzt werden.");

        var liveDetection = File.ReadAllText(liveDetectionPath);
        var status = File.ReadAllText(statusPath);
        var playerWindowPartials = string.Join(
            Environment.NewLine,
            Directory.EnumerateFiles(windowsRoot, "PlayerWindow*.cs")
                .Select(File.ReadAllText));
        var pulse = File.ReadAllText(pulsePath);
        var codingState = File.ReadAllText(codingStatePath);
        var errorWorkflow = File.ReadAllText(errorWorkflowPath);
        var snapshotWorkflow = File.ReadAllText(snapshotWorkflowPath);
        var runCommandWorkflow = File.Exists(runCommandWorkflowPath) ? File.ReadAllText(runCommandWorkflowPath) : "";
        var pulseWorkflow = File.Exists(pulseWorkflowPath) ? File.ReadAllText(pulseWorkflowPath) : "";
        var pulseState = File.Exists(pulseStatePath) ? File.ReadAllText(pulseStatePath) : "";
        var codingAiStateWorkflow = File.Exists(codingAiStateWorkflowPath) ? File.ReadAllText(codingAiStateWorkflowPath) : "";
        var uiDispatchWorkflow = File.Exists(uiDispatchWorkflowPath) ? File.ReadAllText(uiDispatchWorkflowPath) : "";
        var controls = File.ReadAllText(controlsPath);
        var pulseControls = File.Exists(pulseControlsPath) ? File.ReadAllText(pulseControlsPath) : "";

        Assert.DoesNotContain("private void SetLiveDetectionBadge", liveDetection);
        Assert.DoesNotContain("private void SetYoloStatus", liveDetection);
        Assert.DoesNotContain("private void SetCodingAiState", liveDetection);
        Assert.DoesNotContain("private void StartCodingAiPulse", liveDetection);
        Assert.DoesNotContain("private void StopCodingAiPulse", liveDetection);
        Assert.DoesNotContain("private void UpdateDetectionStatus", liveDetection);
        Assert.Contains("private void SetLiveDetectionBadge", status);
        Assert.Contains("private void SetYoloStatus", status);
        Assert.Contains("private void SetCodingAiState", status);
        Assert.DoesNotContain("private void StartCodingAiPulse", status);
        Assert.DoesNotContain("private void StopCodingAiPulse", status);
        Assert.Contains("private void UpdateDetectionStatus", status);
        Assert.Contains("LiveDetectionPulseWorkflow.Start", pulse);
        Assert.Contains("LiveDetectionPulseWorkflow.Stop", pulse);
        Assert.DoesNotContain("_codingAiPulseRunning", pulse);
        Assert.DoesNotContain("private bool _codingAiPulseRunning", codingState);
        Assert.Contains("private LiveDetectionPulseStateController _codingAiPulseStateController => _codingAiStates.PulseState", codingState);
        Assert.Contains("_codingAiPulseStateController.IsRunning", pulse);
        Assert.Contains("_codingAiPulseStateController.CreateStartActions", pulse);
        Assert.Contains("_codingAiPulseStateController.CreateStopActions", pulse);
        Assert.DoesNotContain("if (_codingAiPulseRunning)", pulse);
        Assert.DoesNotContain("_codingAiPulseRunning = true;", pulse);
        Assert.Contains("public sealed class LiveDetectionPulseStateController", pulseState);
        Assert.Contains("public bool IsRunning", pulseState);
        Assert.Contains("if (request.IsRunning)", pulseWorkflow);
        Assert.Contains("actions.SetRunning()", pulseWorkflow);
        Assert.Contains("actions.StartPulse()", pulseWorkflow);
        Assert.Contains("actions.ClearRunning()", pulseWorkflow);
        Assert.Contains("actions.StopPulse()", pulseWorkflow);
        Assert.Contains("LiveDetectionCodingAiStateWorkflow.Execute", status);
        Assert.DoesNotContain("if (pulse)", status);
        Assert.Contains("request.Pulse", codingAiStateWorkflow);
        Assert.Contains("actions.ShowCodingAiState()", codingAiStateWorkflow);
        Assert.Contains("actions.StartPulse()", codingAiStateWorkflow);
        Assert.Contains("actions.StopPulse()", codingAiStateWorkflow);
        Assert.Contains("PlayerUiDispatchWorkflow.Execute", status);
        Assert.Contains("HasDispatcherAccess: PlayerDispatcherScheduler.HasAccess(Dispatcher)", status);
        Assert.Contains("InvokeOnUi: action => PlayerDispatcherScheduler.Invoke(Dispatcher, action)", liveDetection);
        Assert.Contains("DispatchToUi: action => PlayerDispatcherScheduler.Invoke(Dispatcher, action)", status);
        Assert.DoesNotContain("Dispatcher.Invoke(action)", playerWindowPartials);
        Assert.DoesNotContain("Dispatcher.CheckAccess()", playerWindowPartials);
        Assert.DoesNotContain("Dispatcher.HasShutdownStarted", playerWindowPartials);
        Assert.DoesNotContain("if (!Dispatcher.CheckAccess())", status);
        Assert.DoesNotContain("Dispatcher.Invoke(() => Set", status);
        var dispatcherScheduler = File.ReadAllText(Path.Combine(windowsRoot, "PlayerDispatcherScheduler.cs"));
        Assert.Contains("public static void Invoke", dispatcherScheduler);
        Assert.Contains("public static bool HasAccess", dispatcherScheduler);
        Assert.Contains("public static bool HasShutdownStarted", dispatcherScheduler);
        Assert.Contains("actions.DispatchToUi(actions.Apply)", uiDispatchWorkflow);
        Assert.Contains("actions.Apply()", uiDispatchWorkflow);
        Assert.Contains("LiveDetectionStatusControls.ShowLiveDetectionBadge", status);
        Assert.Contains("LiveDetectionStatusControls.ShowYoloStatus", status);
        Assert.Contains("LiveDetectionStatusControls.ShowCodingAiState", status);
        Assert.Contains("LiveDetectionStatusControls.ShowDetectionStatus", status);
        Assert.Contains("LiveDetectionStatusControls.ShowDetectionError", liveDetection);
        Assert.Contains("LiveDetectionErrorWorkflow.Execute", runCommandWorkflow);
        Assert.Contains("LiveDetectionSnapshotWorkflow.Handle", runCommandWorkflow);
        Assert.DoesNotContain("| Bereit", liveDetection);
        Assert.Contains("| Bereit", snapshotWorkflow);
        Assert.DoesNotContain("msg.Length > 200", liveDetection);
        Assert.Contains("message.Length > 200", errorWorkflow);
        Assert.DoesNotContain("LiveDetectionStatusText.Text = $\"Fehler:", liveDetection);
        Assert.DoesNotContain("AiStatusBadge.Visibility", status);
        Assert.DoesNotContain("YoloStatusBar.Visibility", status);
        Assert.DoesNotContain("TxtCodingAiStatus.Text", status);
        Assert.DoesNotContain("FindingSummaryPanel.Visibility", status);
        Assert.Contains("public static void ShowLiveDetectionBadge", controls);
        Assert.Contains("public static void ShowYoloStatus", controls);
        Assert.Contains("public static void ShowCodingAiState", controls);
        Assert.Contains("public static void ShowDetectionStatus", controls);
        Assert.Contains("LiveDetectionDisplayPolicy.BuildDetectionStatusText", controls);
        Assert.Contains("LiveDetectionDisplayPolicy.BuildFindingSummaryText", controls);
        Assert.Contains("private void StartCodingAiPulse", pulse);
        Assert.Contains("private void StopCodingAiPulse", pulse);
        Assert.Contains("LiveDetectionPulseControls.Start(CodingAiPulseRing)", pulse);
        Assert.Contains("LiveDetectionPulseControls.Stop(CodingAiPulseRing)", pulse);
        Assert.DoesNotContain("DoubleAnimation", pulse);
        Assert.Contains("DoubleAnimation", pulseControls);
        Assert.Contains("public static void Start", pulseControls);
        Assert.Contains("public static void Stop", pulseControls);
    }

    [Fact]
    public void PlayerWindow_live_detection_lifecycle_lives_in_lifecycle_partial()
    {
        var root = FindRepositoryRoot();
        var uiRoot = Path.Combine(root, "src", "AuswertungPro.Next.UI");
        var windowsRoot = Path.Combine(uiRoot, "Views", "Windows");
        var liveDetectionPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.cs");
        var lifecyclePath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Lifecycle.cs");
        var stopPath = Path.Combine(windowsRoot, "PlayerWindow.LiveDetection.Lifecycle.Stop.cs");
        var factoryPath = Path.Combine(uiRoot, "Ai", "LiveDetectionRuntimeFactory.cs");
        var clickWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionClickWorkflow.cs");
        var startupWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionStartupWorkflow.cs");
        var startupDisplayWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionStartupDisplayWorkflow.cs");
        var runtimeStartWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionRuntimeStartWorkflow.cs");
        var stopUiWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionStopUiWorkflow.cs");
        var hideStatusTimerWorkflowPath = Path.Combine(uiRoot, "Ai", "LiveDetectionHideStatusTimerWorkflow.cs");
        var toggleControlsPath = Path.Combine(windowsRoot, "LiveDetectionToggleControls.cs");
        var liveControllerPath = Path.Combine(uiRoot, "Player", "LiveDetectionController.cs");
        var disposableLifecyclePath = Path.Combine(uiRoot, "Player", "DisposableReferenceLifecycle.cs");

        Assert.True(File.Exists(lifecyclePath), "LiveDetection-Start/Stop-Wiring soll in ein eigenes Lifecycle-Partial.");
        Assert.True(File.Exists(stopPath), "LiveDetection-Stop/Cleanup soll aus dem Start-Lifecycle-Partial heraus.");
        Assert.True(File.Exists(factoryPath), "LiveDetection-Runtime-Erzeugung soll ausserhalb von PlayerWindow liegen.");
        Assert.True(File.Exists(clickWorkflowPath), "LiveDetection-Klick-Start/Stop-Entscheidung soll ausserhalb von PlayerWindow orchestriert werden.");
        Assert.True(File.Exists(startupWorkflowPath), "LiveDetection-Startup-Entscheidungen sollen ausserhalb von PlayerWindow orchestriert werden.");
        Assert.True(File.Exists(startupDisplayWorkflowPath), "LiveDetection-Startup-Dialogverdrahtung soll ausserhalb von PlayerWindow liegen.");
        Assert.True(File.Exists(runtimeStartWorkflowPath), "LiveDetection-Runtime-Startreihenfolge soll ausserhalb von PlayerWindow orchestriert werden.");
        Assert.True(File.Exists(stopUiWorkflowPath), "LiveDetection-Stop-UI-Reihenfolge soll ausserhalb der PlayerWindow-Partials liegen.");
        Assert.True(File.Exists(hideStatusTimerWorkflowPath), "LiveDetection-Stop-Status-Hide-Timer soll ausserhalb der PlayerWindow-Partials entschieden werden.");
        Assert.True(File.Exists(toggleControlsPath), "LiveDetection-Toggle-State soll ausserhalb der PlayerWindow-Partials gesetzt werden.");
        Assert.True(File.Exists(liveControllerPath), "LiveDetection-Runtime-Zustand soll im LiveDetectionController liegen.");
        Assert.True(File.Exists(disposableLifecyclePath), "Disposable-Referenz-Lifecycle muss ausserhalb der PlayerWindow-Partials liegen.");

        var liveDetection = File.ReadAllText(liveDetectionPath);
        var lifecycle = File.ReadAllText(lifecyclePath);
        var stop = File.ReadAllText(stopPath);
        var factory = File.ReadAllText(factoryPath);
        var clickWorkflow = File.Exists(clickWorkflowPath) ? File.ReadAllText(clickWorkflowPath) : "";
        var startupWorkflow = File.Exists(startupWorkflowPath) ? File.ReadAllText(startupWorkflowPath) : "";
        var startupDisplayWorkflow = File.Exists(startupDisplayWorkflowPath) ? File.ReadAllText(startupDisplayWorkflowPath) : "";
        var runtimeStartWorkflow = File.Exists(runtimeStartWorkflowPath) ? File.ReadAllText(runtimeStartWorkflowPath) : "";
        var stopUiWorkflow = File.Exists(stopUiWorkflowPath) ? File.ReadAllText(stopUiWorkflowPath) : "";
        var hideStatusTimerWorkflow = File.Exists(hideStatusTimerWorkflowPath) ? File.ReadAllText(hideStatusTimerWorkflowPath) : "";
        var toggleControls = File.Exists(toggleControlsPath) ? File.ReadAllText(toggleControlsPath) : "";
        var liveController = File.Exists(liveControllerPath) ? File.ReadAllText(liveControllerPath) : "";
        var disposableLifecycle = File.Exists(disposableLifecyclePath) ? File.ReadAllText(disposableLifecyclePath) : "";
        var playerWindowPartials = string.Join(
            Environment.NewLine,
            Directory.EnumerateFiles(windowsRoot, "PlayerWindow*.cs").Select(File.ReadAllText));

        Assert.DoesNotContain("private async void LiveDetection_Click", liveDetection);
        Assert.DoesNotContain("private async Task StartLiveDetectionAsync", liveDetection);
        Assert.DoesNotContain("private void StopLiveDetection", liveDetection);
        Assert.DoesNotContain("private async void LiveDetection_Click", lifecycle);
        Assert.Contains("private void LiveDetection_Click", lifecycle);
        Assert.Contains(".SafeFireAndForget(\"LiveDetectionClick\")", lifecycle);
        Assert.Contains("private async Task HandleLiveDetectionClickAsync", lifecycle);
        Assert.Contains("LiveDetectionClickWorkflow.ExecuteAsync", lifecycle);
        Assert.DoesNotContain("if (_liveDetectionController.IsDetecting)", lifecycle);
        Assert.Contains("private async Task StartLiveDetectionAsync", lifecycle);
        Assert.DoesNotContain("private void StopLiveDetection", lifecycle);
        Assert.Contains("LiveDetectionStartupDisplayWorkflow.StartAsync", lifecycle);
        Assert.DoesNotContain("LiveDetectionStartupWorkflow.StartAsync", lifecycle);
        Assert.Contains("new LiveDetectionStartupActions", lifecycle);
        Assert.Contains("LiveDetectionToggleControls.Uncheck", lifecycle);
        Assert.DoesNotContain("LiveDetectionButton.IsChecked = false", playerWindowPartials);
        Assert.DoesNotContain("AiRuntimeSettings cfg", lifecycle);
        Assert.DoesNotContain("ShowRuntimeSettingsLoadFailed", lifecycle);
        Assert.DoesNotContain("ShowDisabled", lifecycle);
        Assert.DoesNotContain("ShowStartFailed", lifecycle);
        Assert.DoesNotContain("catch (Exception ex)", lifecycle);
        Assert.DoesNotContain("PlayerAiSettingsLoader.LoadRuntimeSettings", lifecycle);
        Assert.DoesNotContain("AppSettingsAiSettingsProvider", lifecycle);
        Assert.DoesNotContain("LiveDetectionRuntimeFactory.CreateAsync", lifecycle);
        Assert.Contains("_liveDetectionController.StartRuntime", lifecycle);
        Assert.DoesNotContain("LiveDetectionRuntimeStartWorkflow.Start", lifecycle);
        Assert.DoesNotContain("new LiveDetectionRuntimeStartActions", lifecycle);
        Assert.Contains("LiveDetectionRuntimeStartWorkflow.Start", liveController);
        Assert.Contains("new LiveDetectionRuntimeStartActions", liveController);
        Assert.DoesNotContain("\"KI aktiv\"", lifecycle);
        Assert.DoesNotContain("\"Aktiv\"", lifecycle);
        Assert.DoesNotContain("LiveDetectionDisplayPolicy.CompactModelName", lifecycle);
        Assert.Contains("actions.StopLiveDetection()", clickWorkflow);
        Assert.Contains("actions.UncheckToggle()", clickWorkflow);
        Assert.Contains("actions.StartLiveDetectionAsync()", clickWorkflow);
        Assert.Contains("public static class LiveDetectionStartupWorkflow", startupWorkflow);
        Assert.Contains("public static class LiveDetectionStartupDisplayWorkflow", startupDisplayWorkflow);
        Assert.Contains("LiveDetectionDialogServiceFactory.Create", startupDisplayWorkflow);
        Assert.Contains("PlayerAiSettingsLoader.LoadRuntimeSettings", startupDisplayWorkflow);
        Assert.Contains("LiveDetectionRuntimeFactory.CreateAsync", startupDisplayWorkflow);
        Assert.Contains("LiveDetectionStartupWorkflow.StartAsync", startupDisplayWorkflow);
        Assert.Contains("ShowRuntimeSettingsLoadFailed", startupWorkflow);
        Assert.Contains("ShowDisabled", startupWorkflow);
        Assert.Contains("ShowStartFailed", startupWorkflow);
        Assert.Contains("public static class LiveDetectionRuntimeStartWorkflow", runtimeStartWorkflow);
        Assert.Contains("LiveDetectionDisplayPolicy.CompactModelName", runtimeStartWorkflow);
        Assert.Contains("\"KI aktiv\"", runtimeStartWorkflow);
        Assert.Contains("\"Aktiv\"", runtimeStartWorkflow);
        Assert.Contains("public static class LiveDetectionToggleControls", toggleControls);
        Assert.Contains("public static void Uncheck", toggleControls);
        Assert.DoesNotContain("new OllamaClient", lifecycle);
        Assert.DoesNotContain("new LiveDetectionService", lifecycle);
        Assert.DoesNotContain("new DispatcherTimer", lifecycle);
        Assert.DoesNotContain("PlayerWindowTimerFactory.CreateLiveDetectionTimer", lifecycle);
        Assert.Contains("PlayerWindowTimerFactory.CreateLiveDetectionTimer", liveController);
        Assert.Contains("LiveDetectionStatusControls.ShowWaitingForFrame", lifecycle);
        Assert.DoesNotContain("LiveDetectionStatusText.Text = \"Warte auf Frame...\"", lifecycle);
        Assert.DoesNotContain("LiveDetectionStatusText.Visibility = Visibility.Visible", lifecycle);
        Assert.DoesNotContain("VisionModelSelectionPolicy.Select", lifecycle);
        Assert.Contains("new OllamaClient", factory);
        Assert.Contains("new LiveDetectionService", factory);
        Assert.Contains("VisionModelSelectionPolicy.Select", factory);
        Assert.Contains("private void StopLiveDetection", stop);
        Assert.Contains("LiveDetectionStopUiWorkflow.Execute", stop);
        Assert.Contains("LiveDetectionHideStatusTimerWorkflow.Schedule", stop);
        Assert.Contains("_codingSessionHost", stop);
        Assert.DoesNotContain("_codingVm", stop);
        Assert.Contains("public static class LiveDetectionStopUiWorkflow", stopUiWorkflow);
        Assert.Contains("public static class LiveDetectionHideStatusTimerWorkflow", hideStatusTimerWorkflow);
        Assert.Contains("TimeSpan.FromSeconds(5)", hideStatusTimerWorkflow);
        Assert.Contains("PlayerWindowTimerFactory.CreateOneShotTimer", hideStatusTimerWorkflow);
        Assert.Contains("actions.HideDetectionStatus()", hideStatusTimerWorkflow);
        Assert.Contains("LiveDetectionStatusControls.ShowStoppedDetectionStatus", stop);
        Assert.Contains("LiveDetectionStatusControls.HideDetectionStatus", stop);
        Assert.DoesNotContain("if (!_liveDetectionController.IsDetecting)", stop);
        Assert.DoesNotContain("PlayerWindowTimerFactory.CreateOneShotTimer", stop);
        Assert.DoesNotContain("TimeSpan.FromSeconds(5)", stop);
        Assert.DoesNotContain("AiStatusBadge.Visibility", stop);
        Assert.DoesNotContain("FindingSummaryPanel.Visibility", stop);
        Assert.DoesNotContain("LiveDetectionStatusText.Text", stop);
        Assert.DoesNotContain("LiveDetectionStatusText.Visibility = Visibility.Visible", stop);
        Assert.DoesNotContain("LiveDetectionStatusText.Visibility = Visibility.Collapsed", stop);
        Assert.Contains("CancellationTokenSourceLifecycle.CancelPreviousAndCreate", liveController);
        Assert.Contains("CancellationTokenSourceLifecycle.CancelDisposeAndClear", liveController);
        Assert.DoesNotContain("_detectionCts = new CancellationTokenSource();", lifecycle + stop);
        Assert.DoesNotContain("_detectionCts?.Cancel();", lifecycle + stop);
        Assert.DoesNotContain("_detectionCts?.Dispose();", lifecycle + stop);
        Assert.DoesNotContain("_detectionCts = null;", lifecycle + stop);
        Assert.Contains("_client = DisposableReferenceLifecycle.DisposeAndClear(_client)", liveController);
        Assert.DoesNotContain("_liveDetectionClient?.Dispose()", stop);
        Assert.DoesNotContain("_liveDetectionClient = null;", stop);
        Assert.Contains("public static T? DisposeAndClear<T>", disposableLifecycle);
    }
}
