using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace AuswertungPro.Next.Infrastructure.Tests.Import;

/// <summary>
/// Baut kleine kuenstliche XTF-Dateien im ALTEN VSA_KEK-Modell (Version 15.07.2008),
/// wie WinCan VX sie bis heute in <c>Misc\Exchange\...</c> ablegt.
///
/// Anlass (Audit 2026-09-05): Der Ordner "Andermatt Zone 2.11" wird nicht erkannt und
/// seine Schachtbegehungen landen als Haltungen in der Haltungsliste. Diese Klasse
/// bildet genau diese Quelle nach — mit echten Kundendaten darf kein Test laufen.
///
/// Bewusst nur die Felder, die der Leser auch auswertet. Ein Ausbau gehoert zum
/// jeweiligen Arbeitspaket, nicht in einen allgemeinen Generator.
/// </summary>
internal static class AlteVsaKekTestquelle
{
    /// <summary>Eine Haltungsuntersuchung (Kanalfernsehen, von-/bisPunkt, Kanalschaeden).</summary>
    internal sealed record Haltung(
        string Tid,
        string Bezeichnung,
        string VonPunkt,
        string BisPunkt,
        int AnzahlKanalschaeden = 0,
        string Zeitpunkt = "20200702",
        string Operateur = "Pascal Aschwanden");

    /// <summary>Eine Schachtbegehung (Erfassungsart "Begehung", keine Punkte, Normschachtschaeden).</summary>
    internal sealed record Schacht(
        string Tid,
        string Bezeichnung,
        int AnzahlSchachtschaeden = 0,
        string Zeitpunkt = "20200703",
        string Operateur = "Pascal Aschwanden");

    /// <summary>
    /// Eine Untersuchung ohne Erfassungsart, ohne Punkte und ohne Schaeden — der reale
    /// Fall "2204" aus Zone 2.11. Sie darf weder still zur Haltung noch still zum
    /// Schacht werden.
    /// </summary>
    internal sealed record UnklareUntersuchung(
        string Tid,
        string Bezeichnung,
        string Zeitpunkt = "00010101");

    /// <summary>Schreibt die Datei und liefert ihren Pfad zurueck.</summary>
    internal static string SchreibeDatei(
        string zielPfad,
        IEnumerable<Haltung>? haltungen = null,
        IEnumerable<Schacht>? schaechte = null,
        IEnumerable<UnklareUntersuchung>? unklare = null)
    {
        var verzeichnis = Path.GetDirectoryName(zielPfad);
        if (!string.IsNullOrWhiteSpace(verzeichnis))
            Directory.CreateDirectory(verzeichnis);

        File.WriteAllText(zielPfad, BaueXml(haltungen, schaechte, unklare), new UTF8Encoding(false));
        return zielPfad;
    }

    internal static string BaueXml(
        IEnumerable<Haltung>? haltungen = null,
        IEnumerable<Schacht>? schaechte = null,
        IEnumerable<UnklareUntersuchung>? unklare = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("""<?xml version="1.0" encoding="utf-8" standalone="yes"?>""");
        sb.AppendLine("""<TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">""");
        sb.AppendLine("""  <HEADERSECTION VERSION="2.3" SENDER="VSA">""");
        sb.AppendLine("    <MODELS>");
        // Genau die Modellzeilen des echten WinCan-VX-Exports: altes VSA_KEK plus
        // SIA405-Abhaengigkeit im selben Header.
        sb.AppendLine("""      <MODEL NAME="VSA_KEK" VERSION="15.07.2008" URI="http://www.vsa.ch/models" />""");
        sb.AppendLine("""      <MODEL NAME="SIA405_Abwasser" VERSION="15.07.2008" URI="http://www.vsa.ch/models" />""");
        sb.AppendLine("""      <MODEL NAME="SIA405_Base" VERSION="2008.07.03" URI="http://www.interlis.ch/models" />""");
        sb.AppendLine("""      <MODEL NAME="Base" VERSION="2008.07.03" URI="http://www.interlis.ch/models" />""");
        sb.AppendLine("    </MODELS>");
        sb.AppendLine("""    <ALIAS><ENTRIES FOR="VSA_KEK" /></ALIAS>""");
        sb.AppendLine("    <COMMENT>Data generated by WinCan VX, CD Lab AG, www.wincan.com</COMMENT>");
        sb.AppendLine("  </HEADERSECTION>");
        sb.AppendLine("  <DATASECTION>");
        sb.AppendLine("""    <VSA_KEK.KEK BID="chTestBid00000001">""");

        var schadenNummer = 0;

        foreach (var h in haltungen ?? Array.Empty<Haltung>())
        {
            sb.AppendLine($"""      <VSA_KEK.KEK.Untersuchung TID="{h.Tid}">""");
            sb.AppendLine($"        <OBJ_ID>{h.Tid}</OBJ_ID>");
            sb.AppendLine("        <Art>Untersuchung</Art>");
            sb.AppendLine("        <Ausfuehrender>Fretz Kanal-</Ausfuehrender>");
            sb.AppendLine($"        <Bezeichnung>{h.Bezeichnung}</Bezeichnung>");
            sb.AppendLine("        <Grund>Zustandskontrolle</Grund>");
            sb.AppendLine("        <Status>ausgefuehrt</Status>");
            sb.AppendLine($"        <Zeitpunkt>{h.Zeitpunkt}</Zeitpunkt>");
            sb.AppendLine($"""        <AbwasserbauwerkRef REF="{h.Tid}" />""");
            sb.AppendLine($"        <vonPunktBezeichnung>{h.VonPunkt}</vonPunktBezeichnung>");
            sb.AppendLine($"        <bisPunktBezeichnung>{h.BisPunkt}</bisPunktBezeichnung>");
            sb.AppendLine("        <Erfassungsart>Kanalfernsehen</Erfassungsart>");
            sb.AppendLine("        <Inspizierte_Laenge>42.50</Inspizierte_Laenge>");
            sb.AppendLine($"        <Operateur>{h.Operateur}</Operateur>");
            sb.AppendLine("      </VSA_KEK.KEK.Untersuchung>");

            for (var i = 0; i < h.AnzahlKanalschaeden; i++)
            {
                schadenNummer++;
                var meter = (i + 1) * 2.5;
                sb.AppendLine($"""      <VSA_KEK.KEK.Kanalschaden TID="chKS{schadenNummer:D12}">""");
                sb.AppendLine($"        <OBJ_ID>chKS{schadenNummer:D12}</OBJ_ID>");
                sb.AppendLine($"""        <UntersuchungRef REF="{h.Tid}" />""");
                sb.AppendLine("        <KanalSchadencode>BAB</KanalSchadencode>");
                sb.AppendLine($"        <Distanz>{meter.ToString("F2", CultureInfo.InvariantCulture)}</Distanz>");
                sb.AppendLine("        <Einzelschadenklasse>3</Einzelschadenklasse>");
                sb.AppendLine("      </VSA_KEK.KEK.Kanalschaden>");
            }
        }

        foreach (var s in schaechte ?? Array.Empty<Schacht>())
        {
            sb.AppendLine($"""      <VSA_KEK.KEK.Untersuchung TID="{s.Tid}">""");
            sb.AppendLine($"        <OBJ_ID>{s.Tid}</OBJ_ID>");
            sb.AppendLine("        <Art>Untersuchung</Art>");
            sb.AppendLine("        <Ausfuehrender>Fretz Kanal-</Ausfuehrender>");
            sb.AppendLine($"        <Bezeichnung>{s.Bezeichnung}</Bezeichnung>");
            sb.AppendLine("        <Grund>Zustandskontrolle</Grund>");
            sb.AppendLine("        <Status>ausgefuehrt</Status>");
            sb.AppendLine($"        <Zeitpunkt>{s.Zeitpunkt}</Zeitpunkt>");
            sb.AppendLine($"""        <AbwasserbauwerkRef REF="{s.Tid}" />""");
            sb.AppendLine("        <Erfassungsart>Begehung</Erfassungsart>");
            sb.AppendLine("        <Inspizierte_Laenge>2.61</Inspizierte_Laenge>");
            sb.AppendLine($"        <Operateur>{s.Operateur}</Operateur>");
            sb.AppendLine("      </VSA_KEK.KEK.Untersuchung>");

            for (var i = 0; i < s.AnzahlSchachtschaeden; i++)
            {
                schadenNummer++;
                var meter = 0.4 * (i + 1);
                sb.AppendLine($"""      <VSA_KEK.KEK.Normschachtschaden TID="chNS{schadenNummer:D12}">""");
                sb.AppendLine($"        <OBJ_ID>chNS{schadenNummer:D12}</OBJ_ID>");
                sb.AppendLine($"""        <UntersuchungRef REF="{s.Tid}" />""");
                // Schreibweise wie im echten WinCan-VX-Export (Andermatt Zone 2.11 gepruft 2026-09-05).
                sb.AppendLine("        <SchachtSchadencode>DACB</SchachtSchadencode>");
                sb.AppendLine($"        <Distanz>{meter.ToString("F2", CultureInfo.InvariantCulture)}</Distanz>");
                sb.AppendLine("        <Einzelschadenklasse>2</Einzelschadenklasse>");
                sb.AppendLine("      </VSA_KEK.KEK.Normschachtschaden>");
            }
        }

        foreach (var u in unklare ?? Array.Empty<UnklareUntersuchung>())
        {
            sb.AppendLine($"""      <VSA_KEK.KEK.Untersuchung TID="{u.Tid}">""");
            sb.AppendLine($"        <OBJ_ID>{u.Tid}</OBJ_ID>");
            sb.AppendLine("        <Art>Untersuchung</Art>");
            sb.AppendLine($"        <Bezeichnung>{u.Bezeichnung}</Bezeichnung>");
            sb.AppendLine($"        <Zeitpunkt>{u.Zeitpunkt}</Zeitpunkt>");
            sb.AppendLine($"""        <AbwasserbauwerkRef REF="{u.Tid}" />""");
            sb.AppendLine("        <Operateur />");
            sb.AppendLine("      </VSA_KEK.KEK.Untersuchung>");
        }

        sb.AppendLine("    </VSA_KEK.KEK>");
        sb.AppendLine("  </DATASECTION>");
        sb.AppendLine("</TRANSFER>");
        return sb.ToString();
    }
}
