using System;
using System.IO;
using System.Linq;
using System.Text;
using AuswertungPro.Next.Application.Import;
using AuswertungPro.Next.Domain.Models;
using AuswertungPro.Next.Infrastructure.Import;
using AuswertungPro.Next.Infrastructure.Import.Kins;
using AuswertungPro.Next.Infrastructure.Import.WinCan;
using AuswertungPro.Next.Infrastructure.Import.Xtf;
using UglyToad.PdfPig.Content;
using UglyToad.PdfPig.Core;
using UglyToad.PdfPig.Fonts.Standard14Fonts;
using UglyToad.PdfPig.Writer;
using Xunit;

namespace AuswertungPro.Next.Infrastructure.Tests.Import;

/// <summary>
/// Ein-Knopf-Import fuer KINS-DVD-Exporte: massgebliche Quelle VSAKEK-XTF,
/// angereichert aus kiDVDaten.txt (Timecodes/Laenge) und FoxPro-DBF
/// (Stammdaten/Schaechte); Videos + Einzelprotokoll-PDFs werden je Haltung
/// verteilt und relativ verlinkt. Zweiter Lauf muss idempotent sein.
/// </summary>
public sealed class ProjectImportOrchestratorKinsTests : IDisposable
{
    private readonly string _root;

    public ProjectImportOrchestratorKinsTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "KinsOrchestratorTests_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { }
    }

    // -----------------------------------------------------------------------
    // Mini-KINS-Fixture: TXT + XTF (mit SIA405-Modellnamen!) + Video + PDFs + DBF
    // -----------------------------------------------------------------------

    private (string SourceDir, string ProjectDir) ErstelleMiniKinsFixture()
    {
        var sourceDir = Path.Combine(_root, "quelle");
        var projectDir = Path.Combine(_root, "projekt");
        Directory.CreateDirectory(sourceDir);
        Directory.CreateDirectory(projectDir);
        Directory.CreateDirectory(Path.Combine(sourceDir, "VSAKEK"));
        Directory.CreateDirectory(Path.Combine(sourceDir, "048473_DP_Gross"));
        Directory.CreateDirectory(Path.Combine(sourceDir, "DBA"));

        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
        File.WriteAllText(Path.Combine(sourceDir, "kiDVDaten.txt"),
            "Kanalisation 58951 -> 58950 B 600 @Datei=video1.mp4\n" +
            "\t   0.0m Rohranfang  @Pos=0:00:00     \n" +
            "\t  20.5m Inkrustation an der Rohrverbindung 12 Uhr  @Pos=0:06:07     \n" +
            "\t  30.4m Rohrende  @Pos=0:08:51     \n",
            Encoding.GetEncoding(1252));
        File.WriteAllText(Path.Combine(sourceDir, "kiDVinfo.txt"),
            "Medienname: 01-2026\n6460 Altdorf UR\n\nKanalisation\n\nAufnahmen: 24.06.26\n",
            Encoding.GetEncoding(1252));

        // KINS-typisches XTF: SIA405-Modellnamen im Header, Bezeichnung numerisch,
        // Inspizierte_Laenge=0, Video-Datei-Element auf mp4 im Export-Root.
        var xtf = """
<?xml version="1.0" encoding="UTF-8"?>
<TRANSFER xmlns="http://www.interlis.ch/INTERLIS2.3">
  <HEADERSECTION SENDER="VSA" VERSION="2.3">
    <MODELS>
      <MODEL NAME="SIA405_Base_Abwasser_LV95" />
      <MODEL NAME="SIA405_ABWASSER_2020_LV95" />
      <MODEL NAME="VSA_KEK_2020_LV95" />
    </MODELS>
    <COMMENT>Dataset Generated by KINS (R) Kanal Informatik GmbH www.kins.ch</COMMENT>
  </HEADERSECTION>
  <DATASECTION>
    <VSA_KEK_2020_LV95.KEK BID="B1">
      <VSA_KEK_2020_LV95.KEK.Untersuchung TID="U1">
        <Bezeichnung>10</Bezeichnung>
        <Zeitpunkt>20260624</Zeitpunkt>
        <Inspizierte_Laenge>0</Inspizierte_Laenge>
        <vonPunktBezeichnung>58951</vonPunktBezeichnung>
        <bisPunktBezeichnung>58950</bisPunktBezeichnung>
      </VSA_KEK_2020_LV95.KEK.Untersuchung>
      <VSA_KEK_2020_LV95.KEK.Kanalschaden TID="S1">
        <UntersuchungRef REF="U1" />
        <KanalSchadencode>BCD</KanalSchadencode>
        <Distanz>0.00</Distanz>
      </VSA_KEK_2020_LV95.KEK.Kanalschaden>
      <VSA_KEK_2020_LV95.KEK.Kanalschaden TID="S2">
        <UntersuchungRef REF="U1" />
        <KanalSchadencode>BBBA</KanalSchadencode>
        <Distanz>20.50</Distanz>
      </VSA_KEK_2020_LV95.KEK.Kanalschaden>
      <VSA_KEK_2020_LV95.KEK.Kanalschaden TID="S3">
        <UntersuchungRef REF="U1" />
        <KanalSchadencode>BCE</KanalSchadencode>
        <Distanz>30.40</Distanz>
      </VSA_KEK_2020_LV95.KEK.Kanalschaden>
      <VSA_KEK_2020_LV95.KEK.Datei TID="D1">
        <Art>Film</Art>
        <Klasse>Untersuchung</Klasse>
        <Objekt>U1</Objekt>
        <Bezeichnung>video1.mp4</Bezeichnung>
      </VSA_KEK_2020_LV95.KEK.Datei>
    </VSA_KEK_2020_LV95.KEK>
  </DATASECTION>
</TRANSFER>
""";
        File.WriteAllText(Path.Combine(sourceDir, "VSAKEK", "048473-EXPORT.XTF"), xtf);

        File.WriteAllText(Path.Combine(sourceDir, "video1.mp4"), "dummy-video");
        File.WriteAllText(Path.Combine(sourceDir, "048473_DP_Gross", "048473-Haltung10.pdf"),
            "Dichtheitspruefung nach SIA190:2017 / VSA RL Dicht:2023\nvon Schacht: 58951\nnach Schacht: 58950");
        File.WriteAllText(Path.Combine(sourceDir, "048473_DP_Gross", "048473-Haltung1.pdf"),
            "Dichtheitspruefung nach SIA190:2017 / VSA RL Dicht:2023\nvon Schacht: 111\nnach Schacht: 222");

        // Gesamtprotokoll + Deckblatt (Fake — der Seiten-Split scheitert daran kontrolliert,
        // der Einzel-PDF-Fallback muss trotzdem liefern).
        Directory.CreateDirectory(Path.Combine(sourceDir, "048473_PDF"));
        File.WriteAllText(Path.Combine(sourceDir, "048473_PDF", "048473_Protokoll.pdf"), "%PDF-1.4 gesamtprotokoll-fake");
        File.WriteAllText(Path.Combine(sourceDir, "048473_PDF", "048473_Deckblatt.pdf"), "%PDF-1.4 deckblatt");

        new DbfTestFileBuilder()
            .Feld("NR", 'I', 4)
            .Feld("BEZ", 'C', 25)
            .Feld("TIEFE", 'N', 7, 2)
            .Record(r => r.Int32(1).Text("58951").Text("   2.50"))
            .Record(r => r.Int32(2).Text("58950").Text("   0.00"))
            .Schreiben(Path.Combine(sourceDir, "DBA", "schacht.DBF"));

        new DbfTestFileBuilder()
            .Feld("BEZ", 'C', 51)
            .Feld("S_O", 'I', 4)
            .Feld("S_U", 'I', 4)
            .Feld("STRASSE", 'C', 25)
            .Record(r => r.Text("10").Int32(1).Int32(2).Text("Grünweg"))
            .Schreiben(Path.Combine(sourceDir, "DBA", "haltung.DBF"));

        return (sourceDir, projectDir);
    }

    private static ProjectImportOrchestrator ErzeugeOrchestrator(
        IKinsDvdTextEnricher? kinsDvdTextEnricher = null,
        IKinsDbfWhitelistEnricher? kinsDbfWhitelistEnricher = null)
        => new(
            new XtfImportServiceAdapter(),
            new WinCanDbImportService(),
            new KinsImportService(new WinCanDbImportService(), new FakeIbak()),
            kinsDvdTextEnricher: kinsDvdTextEnricher,
            kinsDbfWhitelistEnricher: kinsDbfWhitelistEnricher);

    private static void WritePdf(string path, params string[] lines)
    {
        using var builder = new PdfDocumentBuilder();
        var font = builder.AddStandard14Font(Standard14Font.Helvetica);
        var page = builder.AddPage(PageSize.A4);
        var y = 780m;
        foreach (var line in lines)
        {
            page.AddText(line, 12, new PdfPoint(40, y), font);
            y -= 18;
        }

        File.WriteAllBytes(path, builder.Build());
    }

    /// <summary>Minimaler IBAK-Fake — der KINS-TXT-Pfad braucht IBAK nie.</summary>
    private sealed class FakeIbak : AuswertungPro.Next.Application.Import.IIbakImportService
    {
        public AuswertungPro.Next.Application.Common.Result<AuswertungPro.Next.Application.Import.ImportStats> ImportIbakExport(
            string exportRoot,
            Project project,
            AuswertungPro.Next.Application.Import.ImportRunContext? ctx = null)
            => AuswertungPro.Next.Application.Common.Result<AuswertungPro.Next.Application.Import.ImportStats>.Fail(
                "FAKE", "nicht implementiert");
    }

    private sealed class RecordingKinsDvdTextEnricher : IKinsDvdTextEnricher
    {
        public int Calls { get; private set; }
        public string? LastPath { get; private set; }

        public KinsDvdTextEnrichmentResult Apply(Project project, string kiDvDatenPath)
        {
            Calls++;
            LastPath = kiDvDatenPath;
            return new KinsDvdTextEnrichmentResult(
                TimecodesGesetzt: 7,
                LaengenGesetzt: 8,
                DatumGesetzt: 9,
                Messages: ["KINS-TXT-Testdienst verwendet."]);
        }
    }

    private sealed class RecordingKinsDbfWhitelistEnricher : IKinsDbfWhitelistEnricher
    {
        public int Calls { get; private set; }
        public string? LastSourceFolder { get; private set; }

        public KinsDbfEnrichmentResult Apply(
            Project project,
            string sourceFolder,
            ImportRunContext? context = null)
        {
            Calls++;
            LastSourceFolder = sourceFolder;
            return new KinsDbfEnrichmentResult(
                HaltungsfelderGesetzt: 4,
                SchaechteNeu: 5,
                SchaechteAktualisiert: 6,
                Messages: ["KINS-DBF-Testdienst verwendet."]);
        }
    }

    [Fact]
    public void Import_Kins_XtfMassgeblich_MitAllenAnreicherungenUndVerteilung()
    {
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var project = new Project();

        var result = ErzeugeOrchestrator().Import(sourceDir, projectDir, project);

        Assert.Equal(KanalExportFormat.Kins, result.Format);

        // Haltung: Name aus Schachtpaar, Laenge aus Rohrende, Strasse aus DBF
        var record = Assert.Single(project.Data);
        Assert.Equal("58951-58950", record.GetFieldValue("Haltungsname"));
        Assert.Equal("30.4", record.GetFieldValue("Haltungslaenge_m"));
        Assert.Equal("Grünweg", record.GetFieldValue("Strasse"));

        // Timecode aus kiDVDaten.txt am BBBA-Eintrag
        var bbba = record.Protocol!.Current.Entries.Single(e => e.Code == "BBBA");
        Assert.Equal("0:06:07", bbba.Mpeg);

        // Schaechte aus schacht.DBF
        Assert.Equal(2, project.SchaechteData.Count);

        // Video verteilt + relativ verlinkt
        var link = record.GetFieldValue("Link");
        Assert.False(Path.IsPathRooted(link), $"Link nicht relativ: {link}");
        Assert.True(File.Exists(Path.Combine(projectDir, link!)), $"Video fehlt: {link}");

        // DP-Kandidaten aus dem DP_Gross-Ordner wurden angefasst (Fake-PDFs sind
        // inhaltlich nicht zuordenbar → als nicht zugeordnet gemeldet, kein Absturz).
        Assert.Contains(result.Messages, m => m.StartsWith("Dichtheitspruefung:", StringComparison.Ordinal));

        // XTF archiviert
        Assert.True(
            Directory.EnumerateFiles(projectDir, "*.XTF", SearchOption.AllDirectories).Any(),
            "XTF nicht archiviert");
    }

    [Fact]
    public void Import_Kins_UsesInjectedDvdTextEnricher()
    {
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var project = new Project();
        var enricher = new RecordingKinsDvdTextEnricher();

        var result = ErzeugeOrchestrator(enricher).Import(sourceDir, projectDir, project);

        Assert.Equal(1, enricher.Calls);
        Assert.Equal(Path.Combine(sourceDir, "kiDVDaten.txt"), enricher.LastPath);
        Assert.Contains("KINS-TXT-Testdienst verwendet.", result.Messages);
        Assert.Contains(
            "KINS-TXT: 7 Timecodes, 8 Laengen, 9 Daten gesetzt.",
            result.Messages);
    }

    [Fact]
    public void Import_Kins_UsesInjectedDbfWhitelistEnricher()
    {
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var project = new Project();
        var enricher = new RecordingKinsDbfWhitelistEnricher();

        var result = ErzeugeOrchestrator(kinsDbfWhitelistEnricher: enricher)
            .Import(sourceDir, projectDir, project);

        Assert.Equal(1, enricher.Calls);
        Assert.Equal(sourceDir, enricher.LastSourceFolder);
        Assert.Contains("KINS-DBF-Testdienst verwendet.", result.Messages);
        Assert.Contains(
            "KINS-DBF: 4 Haltungsfelder, 5 Schaechte neu, 6 aktualisiert.",
            result.Messages);
    }

    [Fact]
    public void Import_Kins_ZweiterLauf_IstIdempotent()
    {
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var project = new Project();
        var orch = ErzeugeOrchestrator();

        orch.Import(sourceDir, projectDir, project);
        orch.Import(sourceDir, projectDir, project);

        Assert.Single(project.Data); // kein "10"-Duplikat
        Assert.Equal(2, project.SchaechteData.Count);

        var haltungsOrdner = Path.Combine(projectDir, "Haltungen_Verteilt", "58951-58950");
        var duplikate = Directory.EnumerateFiles(haltungsOrdner)
            .Where(f => Path.GetFileNameWithoutExtension(f).EndsWith("_1", StringComparison.Ordinal))
            .ToList();
        Assert.Empty(duplikate);
    }

    [Fact]
    public void FindeGesamtprotokoll_BevorzugtProtokollPdf_IgnoriertDeckblatt()
    {
        var (sourceDir, _) = ErstelleMiniKinsFixture();

        var gefunden = KinsGesamtprotokollLocator.Finde(sourceDir);

        Assert.NotNull(gefunden);
        Assert.EndsWith("048473_Protokoll.pdf", gefunden);
    }

    [Fact]
    public void FindeGesamtprotokoll_OhneProtokollPdf_LiefertNull()
    {
        var dir = Path.Combine(_root, "leer-quelle");
        Directory.CreateDirectory(dir);
        File.WriteAllText(Path.Combine(dir, "irgendwas.pdf"), "%PDF");

        Assert.Null(KinsGesamtprotokollLocator.Finde(dir));
    }

    [Fact]
    public void DichtheitKandidaten_ErkenntSichereDpPdfAusKinsFixture()
    {
        var (sourceDir, _) = ErstelleMiniKinsFixture();

        var kandidaten = DichtheitImportDistributor.FindeKandidaten(sourceDir);

        // Beide sicher erkannten PDFs aus 048473_DP_Gross, aber nichts aus 048473_PDF oder VSAKEK.
        Assert.Equal(2, kandidaten.Count);
        Assert.All(kandidaten, k => Assert.Contains("DP_Gross", k));
    }

    [Fact]
    public void DichtheitKandidaten_ErkenntDichtheitspruefungAuchInDokumenteOrdner()
    {
        var sourceDir = Path.Combine(_root, "ibas-dokumente-dp");
        var dokumente = Path.Combine(sourceDir, "Dokumente");
        Directory.CreateDirectory(dokumente);
        var pruefprotokoll = Path.Combine(dokumente, "260622131802.pdf");
        File.WriteAllText(
            pruefprotokoll,
            "Dichtheitspruefung nach SIA190/VSA (Verfahren Luft)\n" +
            "von Schacht: SS 8993\n" +
            "nach Schacht: SS 10081\n" +
            "Pruefdruck: 200.0 mbar\n" +
            "Pruefresultat: Pruefung bestanden\n" +
            "22.06.2026");

        var kandidaten = DichtheitImportDistributor.FindeKandidaten(sourceDir);

        Assert.Contains(pruefprotokoll, kandidaten);
    }

    [Fact]
    public void DichtheitKandidaten_IgnoriertDichtDateinameOhneDichtheitsInhaltInDokumenteOrdner()
    {
        var sourceDir = Path.Combine(_root, "dokumente-dicht-name");
        var dokumente = Path.Combine(sourceDir, "Dokumente");
        Directory.CreateDirectory(dokumente);
        File.WriteAllText(
            Path.Combine(dokumente, "Dichtheitskonzept_Plan.pdf"),
            "Sanierungsplan\nLeitungsende\nNetzplan");

        var kandidaten = DichtheitImportDistributor.FindeKandidaten(sourceDir);

        Assert.Empty(kandidaten);
    }

    [Fact]
    public void DichtheitVerteilung_DokumentePruefprotokollMitSsPraefixLandetInBestehenderHaltung()
    {
        var sourceDir = Path.Combine(_root, "fretz-dokumente-dp");
        var dokumente = Path.Combine(sourceDir, "Dokumente");
        var projectDir = Path.Combine(_root, "projekt-dp");
        Directory.CreateDirectory(dokumente);
        Directory.CreateDirectory(Path.Combine(projectDir, "Haltungen_Verteilt", "10081-8993"));

        var pruefprotokoll = Path.Combine(dokumente, "260622131802.pdf");
        WritePdf(
            pruefprotokoll,
            "Dichtheitspruefung nach SIA190/VSA (Verfahren Luft)",
            "von Schacht: SS 8993",
            "nach Schacht: SS 10081",
            "Beginn Pruefung: 22.06.2026 13:19:48",
            "Pruefverfahren: Rohrleitungspruefung Pruefdruck: 200.0 mbar",
            "Pruefresultat: Pruefung bestanden");
        var project = new Project();
        var record = new HaltungRecord();
        record.SetFieldValue("Haltungsname", "10081-8993", FieldSource.Manual, userEdited: false);
        project.Data.Add(record);

        var result = DichtheitImportDistributor.Distribute(project, projectDir, sourceDir);

        Assert.True(result.Verteilt == 1, string.Join(Environment.NewLine, result.Messages));
        Assert.Equal(0, result.NichtZugeordnet);
        Assert.True(File.Exists(Path.Combine(
            projectDir,
            "Haltungen_Verteilt",
            "10081-8993",
            "20260622_10081-8993_DP.pdf")));
    }

    [Fact]
    public void DichtheitVerteilung_UeberspringtBereitsVorhandene()
    {
        // Idempotenz-Guard: liegt im Ziel schon eine *_DP*.pdf gleicher Groesse,
        // wird der Kandidat nicht erneut verteilt (keine _01-Duplikate).
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var quelle = Path.Combine(sourceDir, "048473_DP_Gross", "048473-Haltung10.pdf");
        var zielDir = Path.Combine(projectDir, "Haltungen_Verteilt", "58951-58950");
        Directory.CreateDirectory(zielDir);
        File.Copy(quelle, Path.Combine(zielDir, "20260622_58951-58950_DP.pdf"));

        var result = DichtheitImportDistributor.Distribute(new Project(), projectDir, sourceDir);

        Assert.Equal(1, result.Uebersprungen);
    }

    [Fact]
    public void Import_Kins_RenameBenenntVerteilteDateienMit()
    {
        // Nachweis: Die KINS-Verteilung nutzt exakt das Schema von "Haltung Verteilen" —
        // damit greift die bestehende Rename-Logik ohne Aenderung.
        var (sourceDir, projectDir) = ErstelleMiniKinsFixture();
        var project = new Project();
        ErzeugeOrchestrator().Import(sourceDir, projectDir, project);
        var record = Assert.Single(project.Data);

        var rename = AuswertungPro.Next.Application.Common.HoldingRenameService.Rename(
            record, "58951-58950", "99999-88888",
            Path.Combine(projectDir, "projekt.json"));
        Assert.True(rename.Success, rename.ErrorMessage);
        record.SetFieldValue("Haltungsname", "99999-88888", FieldSource.Manual, userEdited: true);

        Assert.True(Directory.Exists(Path.Combine(projectDir, "Haltungen_Verteilt", "99999-88888")));
        Assert.False(Directory.Exists(Path.Combine(projectDir, "Haltungen_Verteilt", "58951-58950")));

        var link = record.GetFieldValue("Link");
        Assert.True(File.Exists(Path.Combine(projectDir, link!)), $"Video nach Rename nicht auffindbar: {link}");
    }

    [Fact]
    public void Import_Kins_OhneXtf_FaelltAufTxtImportZurueck()
    {
        var sourceDir = Path.Combine(_root, "quelle-alt");
        var projectDir = Path.Combine(_root, "projekt-alt");
        Directory.CreateDirectory(sourceDir);
        Directory.CreateDirectory(projectDir);

        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
        File.WriteAllText(Path.Combine(sourceDir, "kiDVDaten.txt"),
            "Kanalisation 58951 -> 58950 B 600 @Datei=video1.mp4\n" +
            "\t  30.4m Rohrende  @Pos=0:08:51     \n",
            Encoding.GetEncoding(1252));
        File.WriteAllText(Path.Combine(sourceDir, "video1.mp4"), "dummy-video");

        var project = new Project();
        var result = ErzeugeOrchestrator().Import(sourceDir, projectDir, project);

        Assert.Equal(KanalExportFormat.Kins, result.Format);
        var record = Assert.Single(project.Data);
        Assert.Equal("58951-58950", record.GetFieldValue("Haltungsname"));
    }
}
