using System;
using System.IO;
using AuswertungPro.Next.Infrastructure.Import;
using Xunit;

namespace AuswertungPro.Next.Infrastructure.Tests;

/// <summary>
/// KINS-Erkennung im KanalExportDetector. Kernpunkt: Ein KINS-DVD-Export
/// (kiDVDaten.txt) enthaelt oft ein VSAKEK-XTF, dessen Header AUCH die
/// SIA405-Modellnamen listet — er darf weder als IKAS noch als Unknown
/// eingestuft werden, sondern als Kins MIT geliefertem XTF-Pfad.
/// </summary>
public sealed class KanalExportDetectorKinsTests : IDisposable
{
    private readonly string _root;

    // Realistischer KINS-XTF-Header: SIA405- UND VSA_KEK-Modelle im MODELS-Block.
    private const string KinsXtfHeader =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
        "<TRANSFER xmlns=\"http://www.interlis.ch/INTERLIS2.3\">\n" +
        "  <HEADERSECTION VERSION=\"2.3\" SENDER=\"VSA\">\n" +
        "    <MODELS>\n" +
        "      <MODEL NAME=\"SIA405_Base_Abwasser_LV95\" VERSION=\"03.11.2020\" URI=\"http://www.vsa.ch/models\"/>\n" +
        "      <MODEL NAME=\"SIA405_ABWASSER_2020_LV95\" VERSION=\"26.06.2021\" URI=\"http://www.sia.ch/405\"/>\n" +
        "      <MODEL NAME=\"VSA_KEK_2020_LV95\" VERSION=\"03.05.2021\" URI=\"http://www.vsa.ch/models\"/>\n" +
        "    </MODELS>\n" +
        "    <COMMENT>Dataset Generated by KINS (R) Kanal Informatik GmbH www.kins.ch</COMMENT>\n" +
        "  </HEADERSECTION>\n" +
        "</TRANSFER>";

    public KanalExportDetectorKinsTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "KinsDetectorTests_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { }
    }

    private string SchreibeKiDvDaten()
    {
        var path = Path.Combine(_root, "kiDVDaten.txt");
        File.WriteAllText(path, "Kanalisation 58951 -> 58950 B 600 @Datei=video.mp4\n\t   0.0m Rohranfang  @Pos=0:00:00\n");
        return path;
    }

    [Fact]
    public void Detect_KinsMitVsaKekXtf_WirdAlsKinsErkannt_MitXtfPfad()
    {
        var txt = SchreibeKiDvDaten();
        var xtfDir = Directory.CreateDirectory(Path.Combine(_root, "VSAKEK")).FullName;
        var xtf = Path.Combine(xtfDir, "048473-EXPORT.XTF");
        File.WriteAllText(xtf, KinsXtfHeader);

        var det = KanalExportDetector.Detect(_root);

        Assert.Equal(KanalExportFormat.Kins, det.Format);
        Assert.Equal(txt, det.KinsDataTxtPath);
        Assert.Equal(xtf, det.VsaKekXtfPath); // trotz SIA405-Modellnamen im Header!
    }

    [Fact]
    public void Detect_NurKiDvDaten_OhneXtf_WirdAlsKinsErkannt()
    {
        SchreibeKiDvDaten();

        var det = KanalExportDetector.Detect(_root);

        Assert.Equal(KanalExportFormat.Kins, det.Format);
        Assert.NotNull(det.KinsDataTxtPath);
        Assert.Null(det.VsaKekXtfPath);
    }

    [Fact]
    public void Detect_KinsUndWinCan_IstMehrdeutig()
    {
        SchreibeKiDvDaten();
        var dbDir = Directory.CreateDirectory(Path.Combine(_root, "DB")).FullName;
        File.WriteAllText(Path.Combine(dbDir, "projekt.db3"), "dummy");

        var det = KanalExportDetector.Detect(_root);

        Assert.Equal(KanalExportFormat.Ambiguous, det.Format);
    }

    [Fact]
    public void Detect_ReinesVsaKekXtfOhneKiDvDaten_BleibtIkas()
    {
        // Bestehendes IKAS-Verhalten darf sich nicht aendern.
        var xtf = Path.Combine(_root, "export.xtf");
        File.WriteAllText(xtf, "<TRANSFER><MODEL NAME=\"VSA_KEK_2020_LV95\"/></TRANSFER>");

        var det = KanalExportDetector.Detect(_root);

        Assert.Equal(KanalExportFormat.Ikas, det.Format);
        Assert.Null(det.KinsDataTxtPath);
    }
}
